# Generated by Django 4.2.4 on 2023-09-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therestaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('covers', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
