# Generated by Django 4.2.4 on 2023-09-11 20:59

from django.db import migrations, models
import django.db.models.deletion
import therestaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('therestaurant', '0003_reservation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True)),
                ('table_covers', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(default=therestaurant.models.get_default_table, on_delete=django.db.models.deletion.CASCADE, to='therestaurant.table'),
        ),
    ]
