# Generated by Django 4.2.4 on 2023-11-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therestaurant', '0005_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='contact_number',
            field=models.CharField(),
        ),
    ]
