# Generated by Django 4.2.4 on 2023-11-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therestaurant', '0006_alter_reservation_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
    ]
